image: mcr.microsoft.com/playwright:focal

before_script:
  - corepack enable
  - corepack prepare pnpm@latest --activate

stages:
  - test

test:
  stage: test

  script:
    - pnpm install
    - pnpm run test
  artifacts:
    paths:
      - test-results/
      - playwright-report/
    expire_in: 7d
    reports:
      junit: test-results/results.xml
