name: Playwright BDD Tests

permissions:
  contents: read
  checks: write
  id-token: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-bdd-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      # Update to a newer stable Playwright image if available:
      # Check https://hub.docker.com/_/microsoft-playwright for the latest stable version.
      image: mcr.microsoft.com/playwright:v1.51.1-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: pnpm/action-setup@v4

      - name: Set up Node.js and PNPM with caching
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpx playwright install chromium

      - name: Run tests
        run: pnpm run test

      - name: Upload test artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-bdd-results
          overwrite: true
          if-no-files-found: error
          retention-days: 7
          path: |
            test-results/
            playwright-report/

      - name: Publish test report
        uses: mikepenz/action-junit-report@v5
        if: ${{ !cancelled() }}
        with:
          report_paths: test-results/**/*.xml
