name: Playwright BDD Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    container:
      # Update to a newer stable Playwright image if available:
      # Check https://hub.docker.com/_/microsoft-playwright for the latest stable version.
      image: mcr.microsoft.com/playwright:v1.49.0-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: pnpm/action-setup@v4

      - name: Set up Node.js and PNPM with caching
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpx playwright install chromium

      - name: Run tests
        run: pnpm run test

      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
